#!/usr/bin/expect
set timeout 10
set host [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set hostname [lindex $argv 3]
spawn ssh -p 22 $username@$host "sed -i s/^HOST.*/HOSTNAME=$hostname/ /etc/sysconfig/network; hostname $hostname"
expect {
  "(yes/no)?"
  {
   send "yes\n"
   expect "*assword:" { send "$password\n"}
  }
  "*assword:"
  {
   send "$password\n"
  }
}
expect "100%"
#expect eof
exit 0
